controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
# Register user
register:
  path: /api/register
  controller: App\Controller\UserController::register
  methods: [POST]

# Email de confirmation
confirm_email:
  path: /api/confirm-email/{token}
  controller: App\Controller\UserController::confirmEmail
  methods: [GET]

# Connexion user
api_login_check:
  path: /api/login_check

api_refresh_token:
  path: /api/token/refresh

api_token_invalidate:
  path: /api/token/invalidate

# Deconnexion user
logout:
  path: /api/logout
  controller: 'App\Controller\UserController::logout'
  methods: ["GET"]

# Reinitialisation mot de passe- envoi de mot de passe
reset_password:
  path: /api/reset-password
  controller: App\Controller\UserController::resetPassword
  methods: [GET, POST]

# Reinitialisation mot de passe - avec nouveau mot de passe
reset_password_from_link:
  path: /api/reset-password/{token}
  controller: App\Controller\UserController::resetPasswordFromLink
  methods: [GET, POST]

# Suppression de compte
delete_account:
  path: /api/delete-account
  controller: App\Controller\UserController::deleteAccount
  methods: [DELETE]

# Modification de compte
modify_account:
  path: /api/modify-account
  controller: App\Controller\UserController::modifyAccount
  methods: [PUT]

# Admin - Liste des utilisateurs
api_users_list:
  path: "/api/users"
  controller: 'App\Controller\AdminUsersController::getUsers'
  methods: ["POST"]

# Admin - Bannir un utilisateur
api_user_ban:
  path: "/api/users/{id}/ban"
  controller: 'App\Controller\AdminUsersController::banUser'
  methods: ["POST"]
  requirements:
    id: '\d+'

# Admin - Supprimer un utilisateur
api_user_delete:
  path: "/api/users/{id}"
  controller: 'App\Controller\AdminUsersController::deleteUser'
  methods: ["DELETE"]
  requirements:
    id: '\d+'

    # Admin - Supprimer un utilisateur
api_user_change_role:
  path: "/api/users/{id}/change-role"
  controller: 'App\Controller\AdminUsersController::changeUserRole'
  methods: ["PUT"]
  requirements:
    id: '\d+'

# Home - Récupération des nouveaux produits et des produits populaires
api_new_products:
    path: /api/new-products
    controller: App\Controller\HomeController::getNewProducts
    methods: [GET]

api_popular_products:
    path: /api/popular-products
    controller: App\Controller\HomeController::getPopularProducts
    methods: [GET]
